<a href="https://colab.research.google.com/github/ain115/python/blob/master/%EC%A0%95%EA%B5%90%EC%9C%A4_1%EC%A1%B0_OpenAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install xmltodict

Collecting xmltodict
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Installing collected packages: xmltodict
Successfully installed xmltodict-0.12.0

In [0]:
import requests
import json

from urllib.parse import urlencode, quote_plus
from urllib.request import Request, urlopen
import xmltodict

import pandas as pd

# 상업업무용 부동산 매매 신고정보

## 지역코드와 기간을 설정하여 해당지역, 해당기간의 상업업무용 부동산 매매 신고 자료를 제공하는 상업업무용 부동산 매매 신고 정보 조회

### Open API 사용시 전달해야 할 입력 파라메터 3가지
### 법정동코드 - LAWD_CD (10자리 중 앞 5자리 / 예: 11110 (종로구))
https://www.code.go.kr/stdcode/regCodeL.do

### 계약년월 - DEAL_YMD (예: 201512)

### 서비스키 - serviceKey (인증키)

In [0]:
# API Test
# open_api_url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcNrgTrade?LAWD_CD=11110&DEAL_YMD=201512&serviceKey=dHqjQmlYRwI0M12xB1y2qIYpliyjgyq5oK0FvzeVHbpTi665iJxzGO%2B3ZL6iLY60xeOFuD2TfUo0RZVdc%2B9Mfg%3D%3D'

# 법정동코드 
# LAWD_CD = '11110'

# 계약년월일
# DEAL_YMD = '201512'

# 인증키 
serviceKey = 'dHqjQmlYRwI0M12xB1y2qIYpliyjgyq5oK0FvzeVHbpTi665iJxzGO%2B3ZL6iLY60xeOFuD2TfUo0RZVdc%2B9Mfg%3D%3D'

def get_search_result_data_frame(LAWD_CD, DEAL_YMD, serviceKey):
  
  open_api_url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcNrgTrade?LAWD_CD='+LAWD_CD+'&DEAL_YMD='+DEAL_YMD+'&serviceKey='+serviceKey


#open_api_url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcNrgTrade'


#call_url = open_api_url + '?'

# 파라미터 연결, utf-8 선언안하면 ascii 코드로 변환되어서 키값이 변조될 수 있습니다.
#params = urlencode({quote_plus('LAWD_CD'):LAWD_CD, quote_plus('DEAL_YMD') : DEAL_YMD, quote_plus('serviceKey') : serviceKey}, encoding='utf-8')

# urllib의 Request로 요청 url로 병합
#request = Request(call_url + params)

  request = Request(open_api_url)

  request.get_method = lambda: 'GET'
  response_body = urlopen(request).read().decode('utf-8')

  parsed = xmltodict.parse(response_body, dict_constructor=dict)
  
  df = pd.DataFrame.from_dict(parsed['response']['body']['items']['item'], orient='columns')
  
  # csv로 저장 
  df.to_csv('search_result.csv',sep=',')
  
  return df

In [0]:
df = get_search_result_data_frame('11110','201812',serviceKey)
df

         거래금액 건물면적    건물주용도  건축년도     년   대지면적  ...     용도지역   월  유형   일   지역코드    층
0      41,400   43       업무  2005  2018   None  ...     일반상업  12  집합   7  11110   11
1   1,050,000  469  제1종근린생활  1961  2018  189.1  ...     일반상업  12  일반  21  11110  NaN
2     142,500  123       숙박  2005  2018   None  ...     일반상업  12  집합   7  11110   13
3       5,000   20  제2종근린생활  2007  2018   None  ...     일반상업  12  집합   1  11110  NaN
4       7,500    4       판매  2007  2018   None  ...     일반상업  12  집합   5  11110    3
5      33,500   72       판매  2007  2018   None  ...     일반상업  12  집합  17  11110    5
6      44,000   57     교육연구  2008  2018   None  ...     일반상업  12  집합  24  11110  NaN
7      83,000  100     교육연구  2008  2018   None  ...     일반상업  12  집합  26  11110  NaN
8     433,000  102  제2종근린생활   NaN  2018  221.5  ...     일반상업  12  일반   3  11110  NaN
9     810,000  467  제1종근린생활  1965  2018   78.7  ...     일반상업  12  일반  19  11110  NaN
10      6,250    6       기타  1992  2018   None  ...     일반상업  12  집합  11  11110  NaN
11      6,250    6       기타  1992  2018   None  ...     일반상업  12  집합  11  11110  NaN
12    222,000  198  제2종근린생활  2017  2018  211.6  ...  제1종일반주거  12  일반  27  11110  NaN
13     40,000  134  제2종근린생활  2003  2018   None  ...  제1종일반주거  12  집합   4  11110  NaN
14    180,000  317  제2종근린생활   NaN  2018   None  ...     일반상업  12  집합   4  11110  NaN
15    345,000  594  제2종근린생활   NaN  2018   None  ...     일반상업  12  집합   4  11110  NaN
16     19,801   14  제1종근린생활   NaN  2018   12.7  ...     일반상업  12  일반   8  11110  NaN
17     88,000  110       판매  2004  2018   None  ...     일반상업  12  집합   4  11110  NaN
18      3,800    4       판매  2004  2018   None  ...     일반상업  12  집합   7  11110  NaN
19     85,000   89       판매  2004  2018   None  ...     일반상업  12  집합  12  11110  NaN
20      7,500   24  제1종근린생활  1967  2018   None  ...     일반상업  12  집합  26  11110  NaN
21      6,500   20  제1종근린생활  1967  2018   None  ...     일반상업  12  집합  28  11110  NaN
22    240,000  150  제2종근린생활   NaN  2018  202.1  ...     일반상업  12  일반  26  11110  NaN
23     23,000   21  제1종근린생활   NaN  2018   None  ...     일반상업  12  집합  26  11110    1
24     20,762   12       숙박  2018  2018   None  ...     일반상업  12  집합   7  11110    7
25     17,000    5  제2종근린생활   NaN  2018   None  ...     일반상업  12  집합  14  11110  NaN
26     23,000   10       판매   NaN  2018   None  ...     일반상업  12  집합  14  11110  NaN
27     50,000   11       판매   NaN  2018   None  ...     일반상업  12  집합  14  11110  NaN
28     18,000   10       판매   NaN  2018   None  ...     일반상업  12  집합  18  11110  NaN
29     18,000   10       판매   NaN  2018   None  ...     일반상업  12  집합  27  11110  NaN
30     18,000   10       판매   NaN  2018   None  ...     일반상업  12  집합  27  11110  NaN
31     50,000    8       판매  1973  2018   None  ...     일반상업  12  집합  29  11110  NaN
32     76,410  151  제2종근린생활  1994  2018   None  ...  제3종일반주거  12  집합   1  11110  NaN
33    193,590  383  제2종근린생활  1994  2018   None  ...  제3종일반주거  12  집합   1  11110  NaN
34     16,000   33       업무  1997  2018   None  ...     일반상업  12  집합  13  11110  NaN
35     14,400   43       업무  1997  2018   None  ...     일반상업  12  집합  18  11110  NaN
36    471,000  668  제2종근린생활  1974  2018  222.1  ...     일반상업  12  일반  20  11110  NaN
37      7,000    6  제2종근린생활  1996  2018   None  ...     일반상업  12  집합  24  11110  NaN
38     27,123   31       업무  1996  2018   None  ...     일반상업  12  집합  26  11110  NaN
39     18,777   21       업무  1996  2018   None  ...     일반상업  12  집합  26  11110  NaN
40    160,000  118       판매  2004  2018   None  ...     일반상업  12  집합   3  11110  NaN
41    290,000  215       판매  2004  2018   None  ...     일반상업  12  집합   3  11110  NaN
42    112,076   93  제2종근린생활  1965  2018  142.5  ...     일반상업  12  일반  18  11110  NaN
43     78,300   35  제2종근린생활  2017  2018   None  ...  제2종일반주거  12  집합   7  11110   31
44     19,400   56       업무  2018  2018   None  ...  제2종일반주거  12  집합  24  11110  NaN

[45 rows x 14 columns]

In [0]:
# # 법정동코드 
# LAWD_CD = '11110'

# # 계약년월일
# DEAL_YMD = '201512'

# # 인증키 
# serviceKey = 'dHqjQmlYRwI0M12xB1y2qIYpliyjgyq5oK0FvzeVHbpTi665iJxzGO%2B3ZL6iLY60xeOFuD2TfUo0RZVdc%2B9Mfg%3D%3D'

# #params = {'LAWD_CD':LAWD_CD, 'DEAL_YMD':DEAL_YMD, 'serviceKey':serviceKey}

# #open_api_url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcNrgTrade?LAWD_CD=11110&DEAL_YMD=201512&serviceKey=dHqjQmlYRwI0M12xB1y2qIYpliyjgyq5oK0FvzeVHbpTi665iJxzGO%2B3ZL6iLY60xeOFuD2TfUo0RZVdc%2B9Mfg%3D%3D'
# open_api_url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcNrgTrade?LAWD_CD='+LAWD_CD+'&DEAL_YMD='+DEAL_YMD+'&serviceKey='+serviceKey


# #open_api_url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcNrgTrade'


# #call_url = open_api_url + '?'

# # 파라미터 연결, utf-8 선언안하면 ascii 코드로 변환되어서 키값이 변조될 수 있습니다.
# #params = urlencode({quote_plus('LAWD_CD'):LAWD_CD, quote_plus('DEAL_YMD') : DEAL_YMD, quote_plus('serviceKey') : serviceKey}, encoding='utf-8')

# # urllib의 Request로 요청 url로 병합
# #request = Request(call_url + params)

# request = Request(open_api_url)

# request.get_method = lambda: 'GET'
# response_body = urlopen(request).read().decode('utf-8')

# parsed = xmltodict.parse(response_body, dict_constructor=dict)

#print(parsed)

# print(parsed['response']['body']['items']['item']) # 서울의 종로구의 2015년 12월자 부동산 매매 정보 반환

In [0]:
# print(parsed['response']['body']['items']['item'][0])

In [0]:
# type(parsed)

In [0]:
# type(parsed['response']['body']['items']['item'])

In [0]:
# df = pd.DataFrame.from_dict(parsed['response']['body']['items']['item'], orient='columns')

In [0]:
# df

In [0]:
# df.to_csv('search_result.csv',sep=',')